import type { Metadata } from "next";
import { Cabin, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// components imports
import { Navbar, Footer } from "@/components/layout";
import { ThemeProvider } from "@/components/theme/theme-provider";

// fonts configurations
const cabinSans = Cabin({
  variable: "--font-cabin-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// fonts configurations
export const metadata: Metadata = {
  title: "Afzaal Ahmad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabinSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
